"""empty message

Revision ID: 3c174c314fb2
Revises: c81d9276d275
Create Date: 2024-07-20 00:25:14.650273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c174c314fb2'
down_revision = 'c81d9276d275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price')
    )
    op.create_table('order__items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=120), nullable=False),
    sa.Column('course_id', sa.String(length=120), nullable=False),
    sa.Column('order_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('quantity')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('methods_of_payment', sa.String(length=120), nullable=False),
    sa.Column('payment_date', sa.String(length=120), nullable=False),
    sa.Column('total', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methods_of_payment'),
    sa.UniqueConstraint('payment_date'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('total')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('order__items')
    op.drop_table('courses')
    # ### end Alembic commands ###
